### ISSUE TITLE
Movement gesture control missing after swapping to knuckles and back

### ISSUE THREAD

**Issue by TwidgeVR** [Nyabsi/driver_leapify#3]
I'm not entirely sure if this is an issue with leapify, SteamVR or VRC itself

After switching back and forth between hand tracking and index knuckles controller tracking a couple of times, I lose the hand tracking movement gestures on my middle fingers, the contact seems to go away.  The other gesture controls remain functional, only movement and rotation are affected.  My off-the-cuff guess is that VRC is confused and expecting the knuckles to be handling movement still.

Absolutely loving this fork otherwise!

**Comment by Nyabsi** [comment]
Hello,

Thank you for the bug report. I unfortunately cannot see how this could be a driver bug, but I won't entirely count that possibility out.

This requires further investigation, I will be reporting my findings as soon as possible.

Thank you for being interested in this project.

**Comment by Nyabsi** [comment]
I've pushed a new [release](https://github.com/Nyabsi/driver_leapify/releases/tag/1.1.2-beta) that *may* mitigate this issue, please let me know if it fixes it.

**Comment by Nyabsi** [comment]
Closing this issue now as resolved, if the issue arises again, feel free to re-open it.

**Comment by TwidgeVR** [comment]
Thanks Nyabsi! I have not encountered this again since your patch so I think that did it!

**Comment by TwidgeVR** [comment]
I was wrong unfortunately, this happened again last night after swapping back and forth a couple of times.  Same behavior as before with only the movement gesture in VRC becoming disabled.  If this seems to be a mishandling of the swap on VRC's end I can make a ticket there instead.

**Comment by Nyabsi** [comment]
Can you send me a video of this happening so I could have more clear understanding of the issue at hand?

**Comment by Nyabsi** [comment]
Please try this: https://github.com/Nyabsi/leapify/actions/runs/10206235155

I had personally few issues, so I changed some code related to pose handling.

**Comment by Nyabsi** [comment]
Made a canny here,

https://feedback.vrchat.com/open-beta/p/1484-vrchat-loses-controller-tracking-regularly-when-switching-between-steamvr-c

Hope it is resolved soon.
